import Foundation

/// Injects text by driving the system pasteboard and a synthesized ⌘V (spec §3,
/// §11, §18.3; D19–D21). SECURITY-CRITICAL — the §2 sequence is exact and its
/// ordering is the whole point:
///
/// 1. Refuse if secure input is active BEFORE touching the pasteboard, so the
///    transcript never transits the clipboard in a password field (fail-closed,
///    P3 — a "restored to original" check alone would miss this leak window).
/// 2. Snapshot the user's clipboard, then 3. always restore it via `defer` on
///    EVERY exit path (success, throw, or abort) so the original is never lost (P4).
/// 4. Clear + 5. write the transcript with conceal markers so clipboard managers
///    don't persist it (D21).
/// 6. Re-check secure input immediately before pasting — focus may have moved to a
///    password field after step 1 (D20).
/// 7. Paste, surfacing accessibility/paste failures rather than swallowing them.
/// 8. Wait `restoreDelay` so the app consumes the paste before the deferred
///    restore lands.
public struct ClipboardPasteInjector: Injector {
    private let pasteboard: Pasteboard
    private let secureInput: SecureInput
    private let keystroke: PasteKeystroke
    private let restoreDelay: Duration

    /// The conceal markers (D21): clipboard managers skip items carrying these.
    private static let markerTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public init(
        pasteboard: Pasteboard,
        secureInput: SecureInput,
        keystroke: PasteKeystroke,
        restoreDelay: Duration = .milliseconds(80)
    ) {
        self.pasteboard = pasteboard
        self.secureInput = secureInput
        self.keystroke = keystroke
        self.restoreDelay = restoreDelay
    }

    public func insert(_ text: String) async throws {
        // 1. Fail-closed BEFORE any pasteboard write — the transcript must never
        //    transit the clipboard while a secure field is focused.
        guard !secureInput.isSecureInputActive() else {
            throw InjectionError.secureInputActive
        }

        // 2. Capture the user's clipboard before clearing it.
        let saved = pasteboard.snapshot()
        // 3. Restore it on EVERY exit path (success, throw, or secure-recheck abort).
        defer { pasteboard.restore(saved) }

        // 4–5. Clear, then write the transcript with the conceal markers.
        pasteboard.clearContents()
        pasteboard.write(PasteboardWriteItem(string: text, markerTypes: Self.markerTypes))

        // 6. Re-check: focus may have moved to a password field since step 1.
        guard !secureInput.isSecureInputActive() else {
            throw InjectionError.secureInputActive
        }

        // 7. Paste, surfacing the failure (never swallowed).
        try keystroke.paste()

        // 8. Let the app consume the paste before the deferred restore lands.
        try? await Task.sleep(for: restoreDelay)
    }
}
