/// Injects text by driving the system pasteboard and a synthesized ⌘V (spec §3,
/// §11, §18.3; D19–D21). SECURITY-CRITICAL — the §2 sequence is exact and its
/// ordering is the whole point:
///
/// 1. Refuse if secure input is active BEFORE touching the pasteboard, so the
///    transcript never transits the clipboard in a password field (fail-closed,
///    P3 — a "restored to original" check alone would miss this leak window).
/// 2. Snapshot the user's clipboard, then 3. always restore it via `defer` on
///    EVERY exit path (success, throw, or abort) so the original is never lost (P4).
/// 4. Clear the pasteboard.
/// 5. Re-check secure input immediately before writing the transcript — focus may
///    have moved after the first guard.
/// 6. Write the transcript as a lazily-provided item with conceal markers so
///    clipboard managers don't persist it (D21). The lazy item hands us a read
///    signal: a consumer reading the string — normally the paste — pulls the data.
/// 7. Re-check secure input immediately before pasting — focus may have moved to a
///    password field after step 1 (D20).
/// 8. Paste, surfacing accessibility/paste failures rather than swallowing them.
/// 9. Wait for the transcript to be READ (normally by the paste) before the
///    deferred restore lands — an event, never a fixed delay, so the restore can
///    never race ahead of a slow target app (the Codex/Electron #4 defect). The
///    `readSafetyNet` timeout covers only a dropped ⌘V: the pathological path,
///    where restoring the user's clipboard is still correct. The read is not
///    provably the paste (see `text-injection.md` on the clipboard-manager caveat).
public struct ClipboardPasteInjector: Injector {
    private let pasteboard: Pasteboard
    private let secureInput: SecureInput
    private let keystroke: PasteKeystroke
    private let readSafetyNet: Duration

    /// The conceal markers (D21): clipboard managers skip items carrying these.
    private static let markerTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public init(
        pasteboard: Pasteboard,
        secureInput: SecureInput,
        keystroke: PasteKeystroke,
        readSafetyNet: Duration = .seconds(3)
    ) {
        self.pasteboard = pasteboard
        self.secureInput = secureInput
        self.keystroke = keystroke
        self.readSafetyNet = readSafetyNet
    }

    public func insert(_ text: String) async throws {
        // 1. Fail-closed BEFORE any pasteboard write — the transcript must never
        //    transit the clipboard while a secure field is focused.
        guard !secureInput.isSecureInputActive() else {
            throw InjectionError.secureInputActive
        }

        // 2. Capture the user's clipboard before clearing it.
        let saved = pasteboard.snapshot()
        // 3. Restore it on EVERY exit path (success, throw, or secure-recheck abort).
        defer { pasteboard.restore(saved) }

        // 4. Clear before the second guard so any aborted write path restores a
        //    known snapshot instead of leaving a stale transcript behind.
        pasteboard.clearContents()

        // 5. Re-check immediately before writing the transcript.
        guard !secureInput.isSecureInputActive() else {
            throw InjectionError.secureInputActive
        }

        // 6. Write the transcript (lazily provided) with the conceal markers.
        let readSignal = pasteboard.writeAwaitingRead(
            PasteboardWriteItem(string: text, markerTypes: Self.markerTypes)
        )

        // 7. Re-check: focus may have moved to a password field since step 1.
        guard !secureInput.isSecureInputActive() else {
            throw InjectionError.secureInputActive
        }

        // 8. Paste, surfacing the failure (never swallowed).
        try keystroke.paste()

        // 9. Restore only once a consumer has READ the transcript (event-driven,
        //    normally the paste), never on a clock. The safety net bounds only a
        //    dropped ⌘V.
        await readSignal.waitUntilRead(safetyNet: readSafetyNet)
    }
}
