import Foundation
import Testing

import SlovoCore
import SlovoTestSupport

// Epic 07 text injection. The load-bearing contract is the ordered pasteboard
// sequence and fail-closed secure-input checks around every transcript write.
@Suite("Epic 07 injection — ClipboardPasteInjector")
struct ClipboardPasteInjectorTests {
    private static let transcript = "запушь PR в GitHub репозиторий"
    private static let originalClip = [
        PasteboardSnapshotItem(typedData: ["public.utf8-plain-text": Data("ORIGINAL-CLIP".utf8)])
    ]

    private static func injector(
        pasteboard: FakePasteboard,
        secure: FakeSecureInput,
        keystroke: FakePasteKeystroke
    ) -> ClipboardPasteInjector {
        ClipboardPasteInjector(
            pasteboard: pasteboard, secureInput: secure, keystroke: keystroke,
            readSafetyNet: .milliseconds(0)
        )
    }

    /// Stated sensitivity: move the initial secure-input guard after `write`,
    /// and this records pasteboard mutations before throwing.
    @Test
    func secureInputActiveWritesNothingAndThrows() async {
        let pasteboard = FakePasteboard()
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [true]),
            keystroke: keystroke
        )

        await #expect(throws: InjectionError.secureInputActive) {
            try await injector.insert(Self.transcript)
        }

        let wrote = pasteboard.ops.contains { if case .write = $0 { return true }; return false }
        let cleared = pasteboard.ops.contains { if case .clear = $0 { return true }; return false }
        #expect(!wrote, "the transcript must not be written when secure input is active; ops=\(pasteboard.ops)")
        #expect(!cleared, "the pasteboard must not be cleared when secure input is active; ops=\(pasteboard.ops)")
        #expect(!pasteboard.ops.contains(.paste), "nothing must be pasted when secure input is active; ops=\(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 0, "no paste must be attempted when secure input is active")
    }

    /// Stated sensitivity: remove the `defer { restore }`, and the original
    /// clipboard is not restored after a paste failure.
    @Test
    func pasteFailureRestoresOriginalClipboard() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .failure(.pasteFailed), recordingInto: pasteboard)
        )

        await #expect(throws: InjectionError.pasteFailed) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "the original clipboard must be restored after a paste failure; ops=\(pasteboard.ops)")
    }

    /// Stated sensitivity: drop the markers (write `markerTypes: []`) → RED.
    @Test
    func writtenItemCarriesConcealedMarkers() async throws {
        let pasteboard = FakePasteboard()
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .success)
        )
        try await injector.insert(Self.transcript)

        let writeOp = pasteboard.ops.compactMap { op -> PasteboardWriteItem? in
            if case .write(let item) = op { return item }; return nil
        }.first
        let markers = writeOp?.markerTypes ?? []
        #expect(markers.contains("org.nspasteboard.ConcealedType"),
                "the written item must carry the Concealed marker; got \(markers)")
        #expect(markers.contains("org.nspasteboard.TransientType"),
                "the written item must carry the Transient marker; got \(markers)")
        #expect(markers.contains("org.nspasteboard.AutoGeneratedType"),
                "the written item must carry the AutoGenerated marker; got \(markers)")
    }

    /// Stated sensitivity: move `paste()` before `write`, and the unified
    /// pasteboard/keystroke timeline no longer matches. The restore lands strictly
    /// after the `.read` (the paste consuming the transcript), never on a clock.
    @Test
    func normalFieldOrdersSnapshotClearWritePasteReadRestore() async throws {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: keystroke
        )
        try await injector.insert(Self.transcript)

        let expectedItem = PasteboardWriteItem(
            string: Self.transcript,
            markerTypes: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        )
        #expect(pasteboard.ops == [.snapshot, .clear, .write(expectedItem), .paste, .read, .restore(Self.originalClip)],
                "ops must be exactly [snapshot, clear, write, paste, read, restore]; got \(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 1, "paste must be attempted exactly once, got \(keystroke.pasteAttempts)")

        let writeIndex = pasteboard.ops.firstIndex { if case .write = $0 { return true }; return false }
        let pasteIndex = pasteboard.ops.firstIndex { $0 == .paste }
        let readIndex = pasteboard.ops.firstIndex { $0 == .read }
        let restoreIndex = pasteboard.ops.firstIndex { if case .restore = $0 { return true }; return false }
        if let writeIndex, let pasteIndex, let readIndex, let restoreIndex {
            #expect(writeIndex < pasteIndex && pasteIndex < readIndex && readIndex < restoreIndex,
                    "restore must fall strictly after the read event; ops=\(pasteboard.ops)")
        } else {
            #expect(Bool(false), "write/paste/read/restore must all be present; ops=\(pasteboard.ops)")
        }
    }

    /// The heart of the #4 fix: the restore is gated on the paste actually READING
    /// the transcript, not a fixed delay. A slow target app (Codex/Electron) that
    /// reads late must NOT have its clipboard restored before it reads.
    /// Stated sensitivity: restore before awaiting the read (the old fixed-delay
    /// behaviour) → `.restore` appears before the manually driven `.read` → RED.
    @Test
    func restoreWaitsForThePasteReadNotATimer() async throws {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        // Posts ⌘V but does NOT itself read — models a slow app reading later.
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard, consumesPaste: false)
        let injector = ClipboardPasteInjector(
            pasteboard: pasteboard,
            secureInput: FakeSecureInput(values: [false, false]),
            keystroke: keystroke,
            readSafetyNet: .seconds(30)  // generous: the read, not the net, must resolve this
        )

        let task = Task { try await injector.insert(Self.transcript) }

        // Let the injector run up to the point where it awaits the read.
        var waited = 0
        while !pasteboard.ops.contains(.paste), waited < 10_000 {
            await Task.yield()
            waited += 1
        }
        #expect(pasteboard.ops.contains(.paste), "the injector must have posted the paste; ops=\(pasteboard.ops)")
        #expect(!pasteboard.ops.contains { if case .restore = $0 { return true }; return false },
                "restore must NOT happen until the paste has read the transcript; ops=\(pasteboard.ops)")

        pasteboard.simulateRead()  // the slow app finally reads the clipboard
        try await task.value

        let readIndex = pasteboard.ops.firstIndex { $0 == .read }
        let restoreIndex = pasteboard.ops.firstIndex { if case .restore = $0 { return true }; return false }
        #expect(readIndex != nil && restoreIndex != nil && readIndex! < restoreIndex!,
                "restore must fall strictly after the read event; ops=\(pasteboard.ops)")
    }

    /// The safety net (NOT the happy path): if the paste is dropped and the
    /// transcript is never read, the user's clipboard is still restored once the
    /// deadline elapses. Stated sensitivity: drop the safety-net timeout → `insert`
    /// hangs forever waiting for a read that never comes → the test times out.
    @Test
    func droppedPasteStillRestoresViaSafetyNet() async throws {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        // A paste that posts but is never consumed (no read).
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard, consumesPaste: false)
        let injector = ClipboardPasteInjector(
            pasteboard: pasteboard,
            secureInput: FakeSecureInput(values: [false, false]),
            keystroke: keystroke,
            readSafetyNet: .milliseconds(0)  // safety net fires immediately
        )

        try await injector.insert(Self.transcript)

        #expect(!pasteboard.ops.contains(.read), "a dropped paste never reads; ops=\(pasteboard.ops)")
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "a dropped paste must still restore the user's clipboard via the safety net; ops=\(pasteboard.ops)")
    }

    /// Stated sensitivity: swallow the denied state, and this no longer throws.
    @Test
    func accessibilityDeniedIsSurfacedAndClipboardRestored() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .failure(.accessibilityDenied), recordingInto: pasteboard)
        )

        await #expect(throws: InjectionError.accessibilityDenied) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "the clipboard must be restored even when paste is denied; ops=\(pasteboard.ops)")
    }

    /// Stated sensitivity: omit the secure-input check immediately before
    /// writing, and a focus race can leave the transcript in the pasteboard.
    @Test
    func secureBeforeWriteWritesNoTranscriptAndDoesNotPaste() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, true]),
            keystroke: keystroke
        )

        await #expect(throws: InjectionError.secureInputActive) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops == [.snapshot, .clear, .restore(Self.originalClip)],
                "secure input before write must clear then restore without writing transcript; ops=\(pasteboard.ops)")
        #expect(!pasteboard.ops.contains { if case .write = $0 { return true }; return false },
                "the transcript must not be written when secure input appears before write; ops=\(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 0,
                "secure input before write must abort before any paste")
        #expect(!pasteboard.ops.contains(.paste), "no `.paste` op may appear; ops=\(pasteboard.ops)")
    }

    /// Stated sensitivity: omit the secure-input check after writing, and the
    /// transcript is pasted after focus moves to a secure field.
    @Test
    func secureAfterWriteRestoresAndDoesNotPaste() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false, true]),
            keystroke: keystroke
        )

        await #expect(throws: InjectionError.secureInputActive) {
            try await injector.insert(Self.transcript)
        }
        let writeCount = pasteboard.ops.filter {
            if case .write = $0 { return true }
            return false
        }.count
        #expect(writeCount == 1, "the after-write guard should run after one transcript write; ops=\(pasteboard.ops)")
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "secure input after write must restore the user's clipboard; ops=\(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 0,
                "secure input after write must abort before any paste")
        #expect(!pasteboard.ops.contains(.paste), "no `.paste` op may appear; ops=\(pasteboard.ops)")
    }
}
