import Foundation
import Testing

import SlovoCore
import SlovoTestSupport

// Epic 07 — Text injection (ClipboardPasteInjector), SECURITY-CRITICAL.
//
// Contract under test (implementer builds `Sources/SlovoCore/Injection/` per
// plan §1/§2; CURRENTLY the WRONG-ON-PURPOSE `_RedScaffold_Injection.swift`
// stub violates the §2 sequence — guard after write, empty markers, no
// defer-restore, no re-check — so the tests below go RED).
//
// `InjectionError` IS Equatable → assert thrown cases with `#expect(throws:)`.
// CI passes `restoreDelay: .milliseconds(0)` (no real sleep — deterministic).
// FIXTURE ANCHOR RULE (P1): synthetic placeholder text + neutral anchors only.
@Suite("Epic 07 injection — ClipboardPasteInjector")
struct ClipboardPasteInjectorTests {
    private static let transcript = "запушь PR в GitHub репозиторий"
    private static let originalClip = [
        PasteboardSnapshotItem(typedData: ["public.utf8-plain-text": Data("ORIGINAL-CLIP".utf8)])
    ]

    private static func injector(
        pasteboard: FakePasteboard,
        secure: FakeSecureInput,
        keystroke: FakePasteKeystroke
    ) -> ClipboardPasteInjector {
        ClipboardPasteInjector(
            pasteboard: pasteboard, secureInput: secure, keystroke: keystroke,
            restoreDelay: .milliseconds(0)
        )
    }

    /// AC-1 — THE LOAD-BEARING ANTI-FALSE-GREEN: secure input active at start ⇒
    /// `.secureInputActive` thrown AND ZERO pasteboard writes (no `.write`, no
    /// `.clear`) — the transcript NEVER transited the pasteboard (P3).
    /// Stated sensitivity: move the secure-input guard AFTER `write` → a `.write`
    /// op appears in `ops` → the ZERO-WRITES assertion fails → RED. A "clipboard
    /// restored to original" assertion ALONE would NOT catch this (the leak window
    /// already happened). (The scaffold guards after write → RED now.)
    @Test
    func secureInputActiveWritesNothingAndThrows() async {
        let pasteboard = FakePasteboard()
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [true]),
            keystroke: keystroke
        )

        await #expect(throws: InjectionError.secureInputActive) {
            try await injector.insert(Self.transcript)
        }

        let wrote = pasteboard.ops.contains { if case .write = $0 { return true }; return false }
        let cleared = pasteboard.ops.contains { if case .clear = $0 { return true }; return false }
        #expect(!wrote, "ZERO-WRITES: the transcript must NEVER be written when secure input is active; ops=\(pasteboard.ops)")
        #expect(!cleared, "ZERO-WRITES: the pasteboard must not even be cleared when secure input is active; ops=\(pasteboard.ops)")
        // …and nothing was pasted either (the timeline carries no `.paste`).
        #expect(!pasteboard.ops.contains(.paste), "ZERO-WRITES: nothing must be pasted when secure input is active; ops=\(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 0, "no paste must be attempted when secure input is active")
    }

    /// AC-2 — restore on ⌘V failure: the pasteboard was written, then `paste()`
    /// throws ⇒ `.pasteFailed` thrown AND `ops` ends with `.restore(saved)` (the
    /// original clipboard is put back, P4).
    /// Stated sensitivity: remove the `defer { restore }` → no `.restore` after the
    /// throw → RED. (The scaffold has no defer-restore → RED now.)
    @Test
    func pasteFailureRestoresOriginalClipboard() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .failure(.pasteFailed), recordingInto: pasteboard)
        )

        await #expect(throws: InjectionError.pasteFailed) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "the original clipboard must be restored after a paste failure; ops=\(pasteboard.ops)")
    }

    /// AC-3 — concealed markers: the written item carries the
    /// Concealed/Transient/AutoGenerated markers so clipboard managers don't
    /// persist the transcript.
    /// Stated sensitivity: drop the markers (write `markerTypes: []`) → RED.
    /// (The scaffold writes empty markers → RED now.)
    @Test
    func writtenItemCarriesConcealedMarkers() async throws {
        let pasteboard = FakePasteboard()
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .success)
        )
        try await injector.insert(Self.transcript)

        let writeOp = pasteboard.ops.compactMap { op -> PasteboardWriteItem? in
            if case .write(let item) = op { return item }; return nil
        }.first
        let markers = writeOp?.markerTypes ?? []
        #expect(markers.contains("org.nspasteboard.ConcealedType"),
                "the written item must carry the Concealed marker; got \(markers)")
        #expect(markers.contains("org.nspasteboard.TransientType"),
                "the written item must carry the Transient marker; got \(markers)")
        #expect(markers.contains("org.nspasteboard.AutoGeneratedType"),
                "the written item must carry the AutoGenerated marker; got \(markers)")
    }

    /// AC-4 — ordering in a normal field: the UNIFIED op timeline is exactly
    /// `[.snapshot, .clear, .write(item), .paste, .restore(saved)]` — the paste
    /// lands in the SAME recorder as the pasteboard ops, so it is pinned strictly
    /// AFTER the write and BEFORE the restore (not a position-less counter).
    /// Stated sensitivity: move `paste()` BEFORE `clear`/`write` (pasting the
    /// user's STALE clipboard instead of the transcript) → the `.paste` op lands
    /// before `.write` → the exact-sequence assertion fails → RED. Reorder /
    /// skip-restore → RED. (The keystroke is wired `recordingInto:` the pasteboard
    /// so the paste is visible in the timeline — closing the Dalek false-green.)
    @Test
    func normalFieldOrdersSnapshotClearWritePasteRestore() async throws {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: keystroke
        )
        try await injector.insert(Self.transcript)

        let expectedItem = PasteboardWriteItem(
            string: Self.transcript,
            markerTypes: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        )
        // The paste is a first-class op in the SAME timeline: snapshot → clear →
        // write → PASTE → restore. A paste-before-write reorder reds this.
        #expect(pasteboard.ops == [.snapshot, .clear, .write(expectedItem), .paste, .restore(Self.originalClip)],
                "ops must be exactly [snapshot, clear, write, paste, restore]; got \(pasteboard.ops)")
        #expect(keystroke.pasteAttempts == 1, "paste must be attempted exactly once, got \(keystroke.pasteAttempts)")

        // Belt-and-suspenders: pin the paste strictly after write and before restore.
        let writeIndex = pasteboard.ops.firstIndex { if case .write = $0 { return true }; return false }
        let pasteIndex = pasteboard.ops.firstIndex { $0 == .paste }
        let restoreIndex = pasteboard.ops.firstIndex { if case .restore = $0 { return true }; return false }
        if let writeIndex, let pasteIndex, let restoreIndex {
            #expect(writeIndex < pasteIndex && pasteIndex < restoreIndex,
                    "paste must fall strictly after write and before restore; ops=\(pasteboard.ops)")
        } else {
            #expect(Bool(false), "write/paste/restore must all be present; ops=\(pasteboard.ops)")
        }
    }

    /// AC-5 — accessibilityDenied surfaced (not swallowed): `paste()` reports a
    /// denied state ⇒ `.accessibilityDenied` thrown AND the `defer` still restored.
    /// Stated sensitivity: swallow the denied state (catch + return) → no throw →
    /// RED. (The scaffold has no defer-restore → the restore half RED now; once a
    /// catch swallows it, the throw half REDs.)
    @Test
    func accessibilityDeniedIsSurfacedAndClipboardRestored() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, false]),
            keystroke: FakePasteKeystroke(outcome: .failure(.accessibilityDenied), recordingInto: pasteboard)
        )

        await #expect(throws: InjectionError.accessibilityDenied) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "the clipboard must be restored even when paste is denied; ops=\(pasteboard.ops)")
    }

    /// ★ RE-CHECK before paste (GAP-D / D20, SECURITY-REQUIRED): focus moves to a
    /// password field mid-flow — clear at start, SECURE on the step-6 re-check.
    /// ⇒ `.secureInputActive` thrown AND the written transcript is removed
    /// (`ops` ends with `.restore(saved)`).
    /// Stated sensitivity: drop the step-6 re-check → the secure-on-re-check case
    /// wrongly pastes (no throw) → RED. (The scaffold has no re-check → it pastes →
    /// RED now.) This proves the §2-step-6 re-check exists.
    @Test
    func secureOnRecheckAbortsAndRestores() async {
        let pasteboard = FakePasteboard(initialSnapshot: Self.originalClip)
        let keystroke = FakePasteKeystroke(outcome: .success, recordingInto: pasteboard)
        let injector = Self.injector(
            pasteboard: pasteboard,
            secure: FakeSecureInput(values: [false, true]),  // clear at start, secure on re-check
            keystroke: keystroke
        )

        await #expect(throws: InjectionError.secureInputActive) {
            try await injector.insert(Self.transcript)
        }
        #expect(pasteboard.ops.last == .restore(Self.originalClip),
                "a secure re-check must abort the paste and restore the written transcript; ops=\(pasteboard.ops)")
        // Zygon MINOR: the re-check must abort BEFORE pasting — inferring from the
        // thrown error alone is false-green (a refactor that threw AFTER paste()
        // would leak the paste into the now-secure field). Assert ZERO paste.
        #expect(keystroke.pasteAttempts == 0,
                "the re-check must abort BEFORE any paste — nothing pasted into the now-secure field")
        #expect(!pasteboard.ops.contains(.paste), "no `.paste` op must appear when the re-check aborts; ops=\(pasteboard.ops)")
    }
}
